## Retrieve gateway public key ###

- name: Retrieve gateway key
  shell: "/usr/local/bin/key-extractor /etc/tinc/{{ network_name }}/hosts/{{ gateway_name }}"
  register: gateway_key_stdout

- name: Set gateway key as fact
  set_fact:
      gateway_key: "{{ gateway_key_stdout.stdout }}"

### Prepare directories ###

- name: Create client temporary directory path
  set_fact:
      client_temp_path: "{{ local_clients_configs_path }}/{{ client.name }}/etc/tinc/{{ network_name }}"

- name: Make sure all temporary directories exists
  file:
      path: "{{ path_to_create }}"
      state: directory
  loop_control:
      loop_var: path_to_create
  loop:
      - "{{ client_temp_path }}/"
      - "{{ client_temp_path }}/hosts"

### Create client configuration ###

- name: Create tinc.conf
  template:
      src: client/etc/tinc/my-network/tinc.conf
      dest: "{{ client_temp_path }}/tinc.conf"
      mode: "u+rw,g+r,o"

- name: Create tinc scripts
  template:
      src: "client/etc/tinc/my-network/{{ item }}"
      dest: "{{ client_temp_path }}/{{ item }}"
      mode: "u+rwx,g+rx,o"
  with_items:
      - tinc-up
      - tinc-down

- name: Create a gateway host file
  template:
      src: client/etc/tinc/my-network/hosts/gateway
      dest: "{{ client_temp_path }}/hosts/{{ gateway_name }}"
      mode: "u+rw,g+rx,o"

- name: Check if client keys exists
  register: client_keys_exists
  stat:
      path: "{{ client_temp_path }}/rsa_key.priv"

- name: Generate client keys
  when: not client_keys_exists.stat.exists
  shell: "tincd -n {{ network_name }} -K -c {{ client_temp_path }}"

- name: Remember public key in the memory
  shell: "/usr/local/bin/key-extractor {{ client_temp_path }}/hosts/{{ client.name }}"
  register: client_key_stdout

- name: Set host key fact
  set_fact:
      client_key: "{{ client_key_stdout.stdout }}"

### Generate the client config ###
- name: Create client (self) host file
  template:
      src: client/etc/tinc/my-network/hosts/client
      dest: "{{ client_temp_path }}/hosts/{{ client.name }}"

### Copy key to the gateway node ###
- name: Create client host file on gateway node
  template:
      src: server/etc/tinc/my-network/hosts/client-template
      dest: "/etc/tinc/{{ network_name }}/hosts/{{ client.name }}"
