#!/bin/sh
ifconfig $INTERFACE hw ether {{ client.hw_ether }} || true
ifconfig $INTERFACE {{ client.ip }} netmask {{ netmask | default("255.255.255.0") }} -arp

{% for subnet in subnets_to_expose %}
ip -4 route add {{ subnet }} dev $INTERFACE
{% endfor %}
